import { Category, Product, Advertisement, User } from '../src/types.ts';

export const INITIAL_CATEGORIES: Omit<Category, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Salem Rice',
    tamilName: 'சேலம் அரிசி',
    description: 'Direct from Salem mills — premium Ponni, Idli rice, Seeraga Samba and daily rice varieties.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Dals & Pulses',
    tamilName: 'பருப்பு வகைகள்',
    description: 'Polished and unpolished high-protein Toor dal, Urad dal, Moong dal, and Chana.',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Oils & Pure Ghee',
    tamilName: 'எண்ணெய் & நெய்',
    description: 'Traditional cold pressed gingelly (nallennai), groundnut oil, and pure aromatic cow ghee.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Flours & Rava',
    tamilName: 'மாவு வகைகள்',
    description: 'Chakki fresh wheat atta, rice flour, idiyappam flour, and roasted wheat rava.',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Spices & Masalas',
    tamilName: 'மசாலா & மளிகை',
    description: 'Salem golden turmeric, Guntur red chillies, coriander, mustard, cumin, and whole spices.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Pongal & Festival Specials',
    tamilName: 'திருவிழா & பொங்கல் சிறப்பு',
    description: 'Traditional round jaggery (Vellam), Salem cashews, raisins, cardamom, and festive kits.',
    image: 'https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
  {
    name: 'Sugar & Salt',
    tamilName: 'சர்க்கரை & உப்பு',
    description: 'Pure organic Nattu Sakkarai (country sugar), crystal sea salt, and refined cane sugar.',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    active: true,
  },
];

export const INITIAL_PRODUCTS: Omit<Product, '_id' | 'createdAt' | 'updatedAt'>[] = [
  {
    name: 'Salem Ponni Boiled Rice (25kg Bag)',
    tamilName: 'சேலம் பொன்னி புழுங்கல் அரிசி (25 கிலோ)',
    description: 'Aged 1-year authentic Salem Ponni rice. Fluffy, non-sticky grains, ideal for everyday family meals and catering.',
    category: 'Salem Rice',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=600&q=80',
    retailPrice: 1450,
    wholesalePrice: 1380,
    wholesaleMinimumQuantity: 4,
    unit: 'bag',
    stock: 120,
    available: true,
    featured: true,
  },
  {
    name: 'BPT Deluxe Ponni Raw Rice (25kg Bag)',
    tamilName: 'பி.பி.டி டீலக்ஸ் பச்சரிசி (25 கிலோ)',
    description: 'Premium slender grain BPT raw rice with delicate natural aroma. Highly demanded for Pongal and special occasions.',
    category: 'Salem Rice',
    image: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&w=600&q=80',
    retailPrice: 1650,
    wholesalePrice: 1560,
    wholesaleMinimumQuantity: 4,
    unit: 'bag',
    stock: 85,
    available: true,
    featured: true,
  },
  {
    name: 'Salem Special Idli Rice (25kg Bag)',
    tamilName: 'சேலம் ஸ்பெஷல் இட்லி அரிசி (25 கிலோ)',
    description: 'Short, plump grains optimized for ultra-soft, fluffy idlis and crispy golden dosas. Trusted by 200+ local tiffin centers.',
    category: 'Salem Rice',
    image: 'https://images.unsplash.com/photo-1589301760014-d929f3979dbc?auto=format&fit=crop&w=600&q=80',
    retailPrice: 1250,
    wholesalePrice: 1180,
    wholesaleMinimumQuantity: 5,
    unit: 'bag',
    stock: 150,
    available: true,
    featured: true,
  },
  {
    name: 'Traditional Seeraga Samba Rice (10kg Bag)',
    tamilName: 'பாரம்பரிய சீரக சம்பா அரிசி (10 கிலோ)',
    description: 'Tiny aromatic rice grains from Cauvery basin, the gold standard for authentic Tamil Nadu Dindigul and Ambur biryanis.',
    category: 'Salem Rice',
    image: 'https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?auto=format&fit=crop&w=600&q=80',
    retailPrice: 1300,
    wholesalePrice: 1210,
    wholesaleMinimumQuantity: 4,
    unit: 'bag',
    stock: 60,
    available: true,
    featured: true,
  },
  {
    name: 'First Grade Salem Toor Dal (1kg)',
    tamilName: 'முதல் தரம் துவரம் பருப்பு (1 கிலோ)',
    description: 'Unpolished, naturally sweet Toor dal cooked quickly into thick aromatic sambar. No synthetic color or heavy oil coating.',
    category: 'Dals & Pulses',
    image: 'https://images.unsplash.com/photo-1596797038530-2c107229654b?auto=format&fit=crop&w=600&q=80',
    retailPrice: 175,
    wholesalePrice: 158,
    wholesaleMinimumQuantity: 10,
    unit: 'kg',
    stock: 240,
    available: true,
    featured: true,
  },
  {
    name: 'Premium Urad Dal Gundu / Whole (1kg)',
    tamilName: 'உளுத்தம் பருப்பு உருண்டை (1 கிலோ)',
    description: 'High fermentation power whole urad dal for high-volume batter yield and unmatched soft idlis.',
    category: 'Dals & Pulses',
    image: 'https://images.unsplash.com/photo-1585994192701-f1a505c8574a?auto=format&fit=crop&w=600&q=80',
    retailPrice: 160,
    wholesalePrice: 142,
    wholesaleMinimumQuantity: 10,
    unit: 'kg',
    stock: 190,
    available: true,
    featured: true,
  },
  {
    name: 'Cold Pressed Gingelly Oil / Nallennai (1 Litre)',
    tamilName: 'செக்கு நல்லெண்ணெய் (1 லிட்டர்)',
    description: 'Traditional wood-pressed sesame oil prepared with palm jaggery. Rich in antioxidants and authentic village taste.',
    category: 'Oils & Pure Ghee',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    retailPrice: 320,
    wholesalePrice: 295,
    wholesaleMinimumQuantity: 5,
    unit: 'litre',
    stock: 95,
    available: true,
    featured: true,
  },
  {
    name: 'Cold Pressed Groundnut Oil (1 Litre)',
    tamilName: 'செக்கு கடலை எண்ணெய் (1 லிட்டர்)',
    description: '100% pure cold-pressed peanut oil with deep nutty aroma, ideal for everyday deep frying and curries.',
    category: 'Oils & Pure Ghee',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=600&q=80',
    retailPrice: 230,
    wholesalePrice: 210,
    wholesaleMinimumQuantity: 5,
    unit: 'litre',
    stock: 110,
    available: true,
    featured: false,
  },
  {
    name: 'Pure Desi Cow Ghee (500ml Jar)',
    tamilName: 'சுத்தமான பசு நெய் (500மி.லி)',
    description: 'Golden granular texture cow ghee with traditional aroma. Perfect topping for hot rice, pongal, and sweets.',
    category: 'Oils & Pure Ghee',
    image: 'https://images.unsplash.com/photo-1628088062854-d1870b4553da?auto=format&fit=crop&w=600&q=80',
    retailPrice: 360,
    wholesalePrice: 330,
    unit: 'piece',
    stock: 75,
    available: true,
    featured: true,
  },
  {
    name: 'Chakki Fresh Whole Wheat Atta (5kg Bag)',
    tamilName: 'சக்கி பிரெஷ் கோதுமை மாவு (5 கிலோ)',
    description: '100% whole grain wheat flour stone ground for soft, fluffy rotis and chapatis without added maida.',
    category: 'Flours & Rava',
    image: 'https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80',
    retailPrice: 260,
    wholesalePrice: 235,
    unit: 'bag',
    stock: 130,
    available: true,
    featured: false,
  },
  {
    name: 'Pure Salem Turmeric Powder / Manjal (500g)',
    tamilName: 'சேலம் விரலி மஞ்சள் தூள் (500 கிராம்)',
    description: 'High curcumin Salem golden turmeric powder with intense color, natural aroma, and medicinal purity.',
    category: 'Spices & Masalas',
    image: 'https://images.unsplash.com/photo-1615485290382-441e4d049cb5?auto=format&fit=crop&w=600&q=80',
    retailPrice: 120,
    wholesalePrice: 105,
    unit: 'packet',
    stock: 160,
    available: true,
    featured: false,
  },
  {
    name: 'Salem Special Whole Cashews W240 (250g)',
    tamilName: 'முந்திரி பருப்பு (250 கிராம்)',
    description: 'Plump, crunchy whole cashew nuts directly sorted for payasam, festive snacks, and wholesale sweet makers.',
    category: 'Pongal & Festival Specials',
    image: 'https://images.unsplash.com/photo-1509912760195-4f6cfd9c0257?auto=format&fit=crop&w=600&q=80',
    retailPrice: 290,
    wholesalePrice: 260,
    unit: 'packet',
    stock: 80,
    available: true,
    featured: true,
  },
  {
    name: 'Organic Nattu Sakkarai / Country Sugar (1kg)',
    tamilName: 'நாட்டு சர்க்கரை (1 கிலோ)',
    description: 'Chemical-free unrefined cane jaggery powder with natural minerals. Healthy substitute for white sugar in tea and coffee.',
    category: 'Sugar & Salt',
    image: 'https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=600&q=80',
    retailPrice: 95,
    wholesalePrice: 82,
    unit: 'kg',
    stock: 210,
    available: true,
    featured: false,
  }
];

export const INITIAL_ADVERTISEMENTS: Omit<Advertisement, '_id' | 'createdAt'>[] = [
  {
    title: 'Salem New Harvest Ponni Rice 25kg Bags',
    tamilTitle: 'புதிய அறுவடை சேலம் பொன்னி அரிசி 25கி மூட்டைகள்',
    subtitle: 'Direct mill prices for homes, grocery shops, and mess caterers.',
    image: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=1400&q=80',
    linkCategory: 'Salem Rice',
    badge: 'Milling Fresh',
    active: true,
  },
  {
    title: 'Festival & Monthly Maligai Provisions Kit',
    tamilTitle: 'மாதாந்திர மளிகை மலிவு விலை பேக்',
    subtitle: 'Order your complete monthly list in Retail or Bulk Wholesale with same-day priority packing.',
    image: 'https://images.unsplash.com/photo-1542838132-92c53300491e?auto=format&fit=crop&w=1400&q=80',
    linkCategory: 'Dals & Pulses',
    badge: 'Save 15% Wholesale',
    active: true,
  },
  {
    title: 'Traditional Wood-Pressed Chekku Oils & Pure Ghee',
    tamilTitle: 'மரச்செக்கு நல்லெண்ணெய் மற்றும் சுத்தமான பசு நெய்',
    subtitle: 'Preserving our Salem culinary heritage with zero chemical blending.',
    image: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=1400&q=80',
    linkCategory: 'Oils & Pure Ghee',
    badge: '100% Pure',
    active: true,
  }
];

export const INITIAL_USERS: (User & { passwordHash: string })[] = [
  {
    _id: 'usr_admin_1',
    name: 'Store Manager',
    email: 'admin@salemrice.com',
    phone: '8973203053',
    role: 'ADMIN',
    passwordHash: 'salemadmin2026',
    address: '14/2, Bazaar Street, Salem Old Town',
    city: 'Salem',
    pincode: '636001',
    businessName: 'Salem Rice & Maligai Head Office'
  },
  {
    _id: 'usr_father_admin',
    name: 'Father (Managing Director)',
    email: 'father@salemrice.com',
    phone: '9443212345',
    role: 'ADMIN',
    passwordHash: 'salemadmin2026',
    address: 'Main Mill Road, Shevapet',
    city: 'Salem',
    pincode: '636002',
    businessName: 'Salem Rice & Maligai Founder'
  },
  {
    _id: 'usr_sample_customer',
    name: 'Karthik Raman',
    email: 'karthik@gmail.com',
    phone: '9876543210',
    role: 'CUSTOMER',
    passwordHash: 'customer123',
    address: '22, Anna Nagar Main Road',
    city: 'Salem',
    pincode: '636007',
    businessName: 'Annam Tiffin Center'
  },
  {
    _id: 'usr_sample_customer_2',
    name: 'Ramesh Kumar',
    email: 'customer@salemrice.com',
    phone: '9876543210',
    role: 'CUSTOMER',
    passwordHash: 'customer123',
    address: '45, Fairlands Main Road',
    city: 'Salem',
    pincode: '636016',
    businessName: 'Kumar Groceries'
  }
];
